title: Modular Page

columns:
  left:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          headline:
            label: Headline
            type: text
          gridbuilder:
            type: gridbuilder
            cols: 6
            gap: 1
            builderfield: builder
  right:
    width: 1/3
    sections:
      pages:
        type: pages
        headline: Subpages
      sidebar:
        type: fields
        fields:
          builder:
            type: builder
            fieldsets:
              quote: # This is a field set. It contains a group of kirby fields. The user can select from these sets to build the content.
                name: Quote # The name option is used as a label for the buttons to add new fieldsets. It is also used as a label in the header of the fieldset, if the label option is not set explicitly (see next line).
                label: Quote by {{citation}} # Optional. The label option can be used to override the header text of the fieldset. The 'mustache' syntax can be used to include the value of any field of the fieldset.
                preview: # Optional. If defined, a preview of the fieldset can be rendered by the specified snippet from within the snippets folder.
                  snippet: blocks/quote
                  css: /assets/css/blocks/quote.css
                defaultView: preview # Optional. If the value "preview" is set, the block will show the preview when the page is loaded in the panel. If the value is a tab name, the respective tab is preselected when the page is loaded. Newly created blocks ignore this value and have the edit mode or the first tab preselected.
                fields:
                  text:
                    label: Quote Text
                    type: textarea
                  citation:
                    label: Citation
                    type: text