title: Modular Page
extends: merkur


tabs:
  merkur:
    label: Content
    columns:
      left:
        width: 2/3
        sections:
          content:
            type: fields
            fields:
              merkur:
                label: Page Builder
                type: builder
                fieldsets:
                  text: blocks/text
  seo:
    label: Seo
    icon: text